"""Initial migration

Revision ID: e4bbbe948b3b
Revises: ede7ac659fb6
Create Date: 2024-07-30 14:34:50.122668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bbbe948b3b'
down_revision = 'ede7ac659fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
